### ISSUE TITLE
Declare LaTeX dependencies via pdf_document(extra_dependencies = ...)

### ISSUE THREAD

**Issue by yihui** [dr-harper/rmarkdown-cookbook#28]
I guess not many people are aware of the `extra_dependencies` argument. It is a much more compact way of using extra LaTeX packages in `pdf_document()`.

**Comment by haozhu233** [comment]
Here is the related PR. In short, people can attach required latex packages using the following syntax.

```
extra_dependencies: ["multirow", "threeparttable"]

extra_dependencies:
    hyperref: ["unicode=true", "breaklinks=true"]
    lmodern: null
```

https://github.com/rstudio/rmarkdown/pull/944
